version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - vbrandl
    labels:
      - dependencies
      - dependabot

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    assignees:
      - vbrandl
    labels:
      - dependabot
      - dependencies

  - package-ecosystem: 'elm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    assignees:
      - vbrandl
    labels:
      - dependabot
      - dependencies
