version: '2'

services:
  gitache:
    build: ./
    restart: always
    environment:
      - CF_ZONE_IDENT=${CF_ZONE_IDENT}
      - CF_AUTH_USER=${CF_AUTH_USER}
      - CF_AUTH_KEY=${CF_AUTH_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
