name: Security Audit

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/.cargo/audit.toml"
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    working-directory: backend

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: backend
